apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: postgresql-sink-binding
spec:
  source:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: oracle19-history
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: postgresql-sink
    properties:
      databaseName: sampledb
      password: redhat
      query: INSERT INTO ot.keys (key,value) VALUES (:#KEY,:#VALUE)
      serverName: postgresql
      username: redhat