kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: grafana
  labels:
    app: strimzi
spec:
  to:
    kind: Service
    name: grafana
    weight: 100
  port:
    targetPort: grafana
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None