apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-19c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-19c
  template:
    metadata:
      labels:
        app: oracle-19c
        selector: oracle-19c
    spec:
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 54321
      containers:
        - name: oracle-19c
          image: quay.io/indhiotechnologies/oracle-database:19.3.0-ee
          env:
          - name: ORACLE_SID
            value: oraclepoc
          - name: ORACLE_PDB
            value: oraclepdb
          - name: ORACLE_PWD
            valueFrom:
              secretKeyRef:
                name: oracledb-secret
                key: oracleRootPassword
          ports:
          - name: main-port
            containerPort: 1521
          - name: em-port
            containerPort: 5500
          volumeMounts:
              - name: oracle-data
                mountPath: /opt/oracle/oradata
          terminationMessagePolicy: File
      serviceName: oracle19c
      serviceAccountName: oracle
      serviceAccount: oracle
      volumes:
        - name: oracle-data
          persistentVolumeClaim:
            claimName: oracle-data