kind: Secret
apiVersion: v1
metadata:
  name: postgresql
  namespace: database-migration
  labels:
    template: postgresql-persistent-template
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
data:
  database-name: c2FtcGxlZGI=
  database-password: cmVkaGF0
  database-user: cmVkaGF0
type: Opaque
